let playerId = localStorage.getItem('zj-player') || null, side='buy', mission=null, state=null, priceTouched=false;
const API_BASE = new URL('.', window.location.href).pathname.replace(/\/$/, '');
const $=id=>document.getElementById(id), money=n=>Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const api=async(path, body)=>{const r=await fetch(API_BASE+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d};
function toast(text){$('toast').textContent=text;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
$('enter').onclick=async()=>{try{const r=await api('/api/join',{name:$('nick').value});playerId=r.player_id;mission=r.mission;localStorage.setItem('zj-player',playerId);$('playername').textContent=$('nick').value||'匿名投资者';$('mission-title').textContent=mission.title;$('mission-text').textContent=mission.text;$('mission-metric').textContent=mission.metric+'：进行中';$('join').style.display='none';if(r.founder)toast('庄家账户已到账：100亿元虚拟资金');tick()}catch(e){toast(e.message)}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{side=b.dataset.side;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('submit').textContent=(side==='buy'?'买入':'卖出')+' ZJ001';$('submit').className='submit '+side});
document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>$('qty').value=b.dataset.n);
$('price').addEventListener('input',()=>priceTouched=true);
$('submit').onclick=async()=>{if(!playerId)return toast('请先进入市场');try{await api('/api/order',{player_id:playerId,side,price:$('price').value,qty:$('qty').value});toast('委托已提交，正在等待撮合');tick()}catch(e){toast(e.message)}};
async function cancelOrder(id){try{await api('/api/cancel',{player_id:playerId,order_id:id});toast('已撤单');tick()}catch(e){toast(e.message)}}
function levels(id, data, prefix, isAsk=false){let rows=[...data].slice(0,5);if(isAsk){rows.reverse();while(rows.length<5)rows.unshift(null)}else{while(rows.length<5)rows.push(null)}$(id).innerHTML=rows.map((x,i)=>{const label=isAsk?5-i:i+1;return `<div class="level"><span>${prefix}${label}</span><b class="${x?(prefix==='卖'?'green':'red'):''}">${x?x.price.toFixed(2):'--'}</b><span>${x?x.qty:'--'}</span></div>`}).join('')}
function draw(candles){const c=$('kline'),ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.clientWidth,H=c.clientHeight;ctx.clearRect(0,0,W,H);if(!candles.length)return;const hi=Math.max(...candles.map(x=>x.high))*1.003,lo=Math.min(...candles.map(x=>x.low))*.997,range=hi-lo;ctx.strokeStyle='#1b2b39';ctx.lineWidth=1;for(let i=1;i<5;i++){let y=H*i/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const step=W/Math.max(candles.length,40),bar=Math.max(2,step*.58);candles.forEach((x,i)=>{let px=(i+.5)*step,oy=(hi-x.open)/range*(H-25),cy=(hi-x.close)/range*(H-25),hy=(hi-x.high)/range*(H-25),ly=(hi-x.low)/range*(H-25),up=x.close>=x.open;ctx.strokeStyle=ctx.fillStyle=up?'#ff4d5e':'#1cc98b';ctx.beginPath();ctx.moveTo(px,hy);ctx.lineTo(px,ly);ctx.stroke();ctx.fillRect(px-bar/2,Math.min(oy,cy),bar,Math.max(1,Math.abs(cy-oy)))});ctx.fillStyle='#708397';ctx.font='11px sans-serif';ctx.fillText(hi.toFixed(2),5,12);ctx.fillText(lo.toFixed(2),5,H-5)}
function render(s){state=s;const positive=s.change>=0;$('last').textContent=s.last.toFixed(2);$('change').textContent=(positive?'+':'')+s.change.toFixed(2)+'%';$('last').className=positive?'red':'green';$('change').className=positive?'red':'green';['open','high','low'].forEach(k=>$(k).textContent=s[k].toFixed(2));$('volume').textContent=s.volume.toLocaleString();$('online').textContent=s.online;$('midprice').textContent=s.last.toFixed(2);if(!priceTouched)$('price').value=s.last.toFixed(2);levels('asks',s.asks,'卖',true);levels('bids',s.bids,'买',false);$('trades').innerHTML=s.trades.map(t=>`<div class="trade"><span>${t.time}</span><b class="${t.side==='buy'?'red':'green'}">${t.price.toFixed(2)}</b><span>${t.qty}</span></div>`).join('')||'<p class="empty">等待成交</p>';if(s.account){$('cash').textContent=money(s.account.cash-s.account.frozen_cash);$('shares').textContent=(s.account.shares-s.account.frozen_shares).toLocaleString();$('equity').textContent=money(s.equity);const p=s.equity-s.account.starting_equity;$('pnl').textContent=(p>=0?'+':'')+money(p);$('pnl').className=p>=0?'red':'green';const prog=Math.max(2,Math.min(92,50+(s.last-10)*400+(s.volume/1000)));$('progress').style.width=prog+'%';$('mission-metric').textContent=(mission?.metric||'任务进度')+'：'+Math.round(prog)+'%';$('pending').innerHTML=s.pending.length?s.pending.map(o=>`<div class="pending-item"><div><b class="${o.side==='buy'?'red':'green'}">${o.side==='buy'?'买入':'卖出'} ${o.price.toFixed(2)}</b><span>剩余 ${o.remaining} 股</span></div><button class="cancel" onclick="cancelOrder('${o.id}')">撤单</button></div>`).join(''):'<p class="empty">暂无挂单</p>'}draw(s.candles)}
async function tick(){if(!playerId)return;try{render(await api('/api/snapshot?player_id='+encodeURIComponent(playerId)))}catch(e){console.warn(e)}}setInterval(tick,700);setInterval(()=>$('clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false}),1000);
