let playerId = localStorage.getItem('zj-player') || null, side='buy', mission=null, state=null, priceTouched=false, klineStep=12, klineInterval=1;
const API_BASE = new URL('.', window.location.href).pathname.replace(/\/$/, '');
const $=id=>document.getElementById(id), money=n=>Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const api=async(path, body)=>{const r=await fetch(API_BASE+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d};
function toast(text){$('toast').textContent=text;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
$('enter').onclick=async()=>{try{const r=await api('/api/join',{name:$('nick').value});playerId=r.player_id;mission=r.mission;localStorage.setItem('zj-player',playerId);$('playername').textContent=$('nick').value||'匿名投资者';$('mission-title').textContent=mission.title;$('mission-text').textContent=mission.text;$('mission-metric').textContent=mission.metric+'：进行中';$('join').style.display='none';if(r.founder)toast('庄家权限已启用：无限虚拟资金');tick()}catch(e){toast(e.message)}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{side=b.dataset.side;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('submit').textContent=(side==='buy'?'买入':'卖出')+' ZJ001';$('submit').className='submit '+side});
document.querySelectorAll('.quick button').forEach(button=>button.onclick=()=>{if(!state?.account)return toast('请先进入市场');const pct=Number(button.dataset.pct),price=Number($('price').value);if(!Number.isFinite(price)||price<=0)return toast('请先填写有效委托价格');const account=state.account,available=side==='buy'?account.cash-account.frozen_cash:account.shares-account.frozen_shares,shares=side==='buy'?Math.floor(available*pct/100/price/100)*100:Math.floor(available*pct/100/100)*100;if(shares<100)return toast('可用资产不足 1 手');$('qty').value=shares});
$('price').addEventListener('input',()=>priceTouched=true);
document.querySelectorAll('.kline-tab').forEach(button=>button.onclick=()=>{klineInterval=Number(button.dataset.kline);document.querySelectorAll('.kline-tab').forEach(tab=>tab.classList.toggle('active',tab===button));$('kline-help').textContent=`${klineInterval}分钟 K线 · ${klineStep}px / 根 · ↑↓ 缩放`;if(state)draw(chartCandles(state.candles))});
window.addEventListener('keydown',event=>{if(event.target.matches('input,textarea,select'))return;if(event.key!=='ArrowUp'&&event.key!=='ArrowDown')return;event.preventDefault();klineStep=Math.max(6,Math.min(28,klineStep+(event.key==='ArrowUp'?2:-2)));$('kline-help').textContent=`${klineInterval}分钟 K线 · ${klineStep}px / 根 · ↑↓ 缩放`;if(state)draw(chartCandles(state.candles))});
$('submit').onclick=async()=>{if(!playerId)return toast('请先进入市场');try{await api('/api/order',{player_id:playerId,side,price:$('price').value,qty:$('qty').value});toast('委托已提交，正在等待撮合');tick()}catch(e){toast(e.message)}};
$('cancel-all').onclick=async()=>{if(!playerId)return toast('请先进入市场');try{const r=await api('/api/cancel-all',{player_id:playerId});toast(r.count?`已撤销 ${r.count} 笔委托`:'当前没有可撤委托');tick()}catch(e){toast(e.message)}};
$('settle').onclick=async()=>{if(!playerId)return toast('请先进入市场');try{const r=await api('/api/settle',{player_id:playerId});toast(`本局已结算：${r.result.return_rate>=0?'+':''}${r.result.return_rate.toFixed(2)}%`);tick()}catch(e){toast(e.message)}};
async function cancelOrder(id){try{await api('/api/cancel',{player_id:playerId,order_id:id});toast('撤单成功');tick()}catch(e){toast(e.message)}}
$('pending').addEventListener('click',event=>{const button=event.target.closest('[data-cancel-id]');if(!button)return;button.disabled=true;cancelOrder(button.dataset.cancelId)});
function levels(id, data, prefix, isAsk=false){let rows=[...data].slice(0,5);if(isAsk){rows.reverse();while(rows.length<5)rows.unshift(null)}else{while(rows.length<5)rows.push(null)}$(id).innerHTML=rows.map((x,i)=>{const label=isAsk?5-i:i+1;return `<div class="level"><span>${prefix}${label}</span><b class="${x?(prefix==='卖'?'green':'red'):''}">${x?x.price.toFixed(2):'--'}</b><span>${x?x.qty:'--'}</span></div>`}).join('')}
function chartCandles(candles){if(klineInterval===1)return candles;const grouped=[];for(const candle of candles){const bucket=Math.floor(candle.time/(klineInterval*60))*klineInterval*60,last=grouped[grouped.length-1];if(!last||last.time!==bucket)grouped.push({time:bucket,open:candle.open,high:candle.high,low:candle.low,close:candle.close,volume:candle.volume});else{last.high=Math.max(last.high,candle.high);last.low=Math.min(last.low,candle.low);last.close=candle.close;last.volume+=candle.volume}}return grouped}
function draw(candles){const c=$('kline'),ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.clientWidth,H=c.clientHeight;ctx.clearRect(0,0,W,H);if(!candles.length)return;const step=klineStep,visible=candles.slice(-Math.max(1,Math.floor(W/step))),start=0,priceH=Math.floor(H*.58),volumeTop=Math.floor(H*.62),volumeH=Math.floor(H*.14),macdTop=Math.floor(H*.80),macdH=H-macdTop-4,hi=Math.max(...visible.map(x=>x.high))*1.003,lo=Math.min(...visible.map(x=>x.low))*.997,range=Math.max(hi-lo,.01),bar=Math.max(2,step*.58);ctx.strokeStyle='#1b2b39';ctx.lineWidth=1;for(let i=1;i<5;i++){let y=priceH*i/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}visible.forEach((x,i)=>{let px=start+(i+.5)*step,oy=(hi-x.open)/range*(priceH-18),cy=(hi-x.close)/range*(priceH-18),hy=(hi-x.high)/range*(priceH-18),ly=(hi-x.low)/range*(priceH-18),up=x.close>=x.open;ctx.strokeStyle=ctx.fillStyle=up?'#ff4d5e':'#1cc98b';ctx.beginPath();ctx.moveTo(px,hy);ctx.lineTo(px,ly);ctx.stroke();ctx.fillRect(px-bar/2,Math.min(oy,cy),bar,Math.max(1,Math.abs(cy-oy)))});const maxVolume=Math.max(1,...visible.map(x=>x.volume));visible.forEach((x,i)=>{const px=start+(i+.5)*step,height=x.volume/maxVolume*volumeH;ctx.fillStyle=x.close>=x.open?'#ff4d5e':'#1cc98b';ctx.fillRect(px-bar/2,volumeTop+volumeH-height,bar,Math.max(1,height))});const closes=visible.map(x=>x.close),ema=period=>{let value=closes[0];return closes.map(price=>(value=value+(price-value)*2/(period+1)))},fast=ema(12),slow=ema(26),dif=fast.map((value,i)=>value-slow[i]),signal=dif.reduce((out,value,i)=>{out.push(i?out[i-1]+(value-out[i-1])*2/10:value);return out},[]),hist=dif.map((value,i)=>(value-signal[i])*2),macdMax=Math.max(.001,...dif.map(Math.abs),...signal.map(Math.abs),...hist.map(Math.abs)),zero=macdTop+macdH/2,macdY=value=>zero-value/macdMax*(macdH/2-3);ctx.strokeStyle='#1b2b39';ctx.beginPath();ctx.moveTo(0,zero);ctx.lineTo(W,zero);ctx.stroke();hist.forEach((value,i)=>{const px=start+(i+.5)*step,y=macdY(value);ctx.fillStyle=value>=0?'#ff4d5e':'#1cc98b';ctx.fillRect(px-bar/2,Math.min(y,zero),bar,Math.max(1,Math.abs(y-zero)))});for(const [line,color] of [[dif,'#ffd166'],[signal,'#35a6ff']]){ctx.strokeStyle=color;ctx.beginPath();line.forEach((value,i)=>{const px=start+(i+.5)*step,y=macdY(value);i?ctx.lineTo(px,y):ctx.moveTo(px,y)});ctx.stroke()}ctx.fillStyle='#708397';ctx.font='11px sans-serif';ctx.fillText(hi.toFixed(2),5,12);ctx.fillText(lo.toFixed(2),5,priceH-3);ctx.fillText('VOL '+Math.round(maxVolume),5,volumeTop+11);ctx.fillText('MACD  DIF 黄  DEA 蓝',5,macdTop+11)}
function render(s){state=s;const positive=s.change>=0;$('last').textContent=s.last.toFixed(2);$('change').textContent=(positive?'+':'')+s.change.toFixed(2)+'%';$('last').className=positive?'red':'green';$('change').className=positive?'red':'green';['open','high','low'].forEach(k=>$(k).textContent=s[k].toFixed(2));$('limit-up').textContent=s.limits[1].toFixed(2);$('limit-down').textContent=s.limits[0].toFixed(2);$('volume').textContent=s.volume.toLocaleString();$('online').textContent=s.online;$('pending-count').textContent=s.pending.length;$('midprice').textContent=s.last.toFixed(2);if(!priceTouched)$('price').value=s.last.toFixed(2);levels('asks',s.asks,'卖',true);levels('bids',s.bids,'买',false);$('trades').innerHTML=s.trades.map(t=>`<div class="trade"><span>${t.time}</span><b class="${t.side==='buy'?'red':'green'}">${t.price.toFixed(2)}</b><span>${t.qty}</span></div>`).join('')||'<p class="empty">等待成交</p>';if(s.account){const unlimited=s.account.unlimited_funds,cost=s.account.avg_cost||0,positionPnl=(s.last-cost)*s.account.shares,returnRate=cost?(s.last/cost-1)*100:0;$('cash').textContent=unlimited?'∞':money(s.account.cash-s.account.frozen_cash);$('shares').textContent=(s.account.shares-s.account.frozen_shares).toLocaleString();$('equity').textContent=unlimited?'∞':money(s.equity);$('cost').textContent=cost.toFixed(2);$('pnl').textContent=(positionPnl>=0?'+':'')+money(positionPnl);$('pnl').className=positionPnl>=0?'red':'green';$('return-rate').textContent=(returnRate>=0?'+':'')+returnRate.toFixed(2)+'%';$('return-rate').className=returnRate>=0?'red':'green';const prog=Math.max(2,Math.min(92,50+(s.last-s.open)*400+(s.volume/1000)));$('progress').style.width=prog+'%';$('mission-metric').textContent=(mission?.metric||'任务进度')+'：'+Math.round(prog)+'%';$('pending').innerHTML=s.pending.length?s.pending.map(o=>`<div class="pending-item"><div><b class="${o.side==='buy'?'red':'green'}">${o.side==='buy'?'买入':'卖出'} ${o.price.toFixed(2)}</b><span>剩余 ${o.remaining} 股</span></div><button type="button" class="cancel" data-cancel-id="${o.id}">撤单</button></div>`).join(''):'<p class="empty">暂无挂单</p>'}draw(chartCandles(s.candles))}
function renderExtras(s){const positive=n=>n>=0?'red':'green',signed=n=>(n>=0?'+':'')+money(n);$('leaderboard').innerHTML=s.leaderboard.length?s.leaderboard.map((row,index)=>`<div class="rank-row"><span>${index+1}</span><b>${row.name}</b><b class="${positive(row.return_rate)}">${row.return_rate>=0?'+':''}${row.return_rate.toFixed(2)}%</b></div>`).join(''):'<p class="empty">等待玩家加入</p>';const performance=s.performance;if(performance){$('realized-pnl').textContent=signed(performance.realized_pnl);$('realized-pnl').className=positive(performance.realized_pnl);$('trade-count').textContent=performance.trade_count+' 笔';$('trade-volume').textContent=performance.trade_volume.toLocaleString()+' 股';$('history').innerHTML=s.history.length?s.history.map(row=>`<div class="history-row"><span>${row.time}</span><b class="${row.side==='买入'?'red':'green'}">${row.side}</b><b>${row.price.toFixed(2)}</b><span>${row.qty} 股</span></div>`).join(''):'<p class="empty">完成成交后，这里会保留最近 30 笔复盘记录</p>'}}
async function tick(){if(!playerId)return;try{const snapshot=await api('/api/snapshot?player_id='+encodeURIComponent(playerId));if(!snapshot.account){localStorage.removeItem('zj-player');playerId=null;mission=null;$('playername').textContent='未登录';$('join').style.display='grid';return}render(snapshot);renderExtras(snapshot)}catch(e){console.warn(e)}}setInterval(tick,700);setInterval(()=>$('clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false}),1000);
